all:
	g++ qconf_client.cc -o qconf_client -L /home/liminghao/source_code/QConf/manager/build/qconf_zk/my_qconf_client ./libqconf_zk.a -I /home/liminghao/source_code/QConf/manager/deps/zookeeper/_install/include/zookeeper -lpthread -g

clean:
	rm -f ./qconf_client
